name: 'Close Stale Issues Safely'
description: 'Close issues with no recent activity'
icon: 'archive'
color: 'purple'
author: 'DeMoorJasper'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  days-before-stale:
    description: 'The number of days old an issue can be before marking it stale'
    default: 60
  days-before-close:
    description: 'The number of days to wait to close an issue or pull request after it being marked stale'
    default: 14
  stale-message:
    description: 'The message to post on the issue when tagging it. If none provided, will not mark issues stale.'
    default: 'This issue has been marked as stale.'
  stale-label:
    description: 'The label to apply when an issue is stale'
    default: 'Stale'
  exempt-labels:
    description: 'Issues with these labels cannor become stale'
    default: 'stale-ignore, security'
  operations-per-run:
    description: 'The maximum number of operations per run, used to control rate limiting, does not apply to dry runs.'
    default: 50
  dry-run:
    description: 'The action will just log what it would do without actually causing any changes to the repo.'
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
